name: Deploy to Test Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup OpenVPN
      run: |
        echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn
        sudo apt-get update
        sudo apt-get install -y openvpn
        sudo openvpn --config client.ovpn --daemon
        sleep 30  # Wait for the VPN connection to establish
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: github
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/snake/testgithub/
          sudo /home/snake/scripts/dev_grant_github.sh
          git pull git@github.com:snbike/slurm.git main
          sudo /home/snake/scripts/dev_grant_admin.sh
